version: '3.9'

services:
  ghcrtest:
    image: ghcr.io/yanorei32/ghcr-test:latest@sha256:76d3314b10626f094329cbe17da4dd5804ce34a530a576059ca5d714eb601732
    hostname: ghcrtest
    container_name: ghcrtest__ghcrtest
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 64m

    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1m

    network_mode: none
